### ISSUE TITLE
GraphicsMagick on Azure

### ISSUE THREAD

**Issue by loretoparisi** [aheckmann/channel9#1]
How did you install GraphicsMagick binaries on Azure? There's no official doc about this.

**Comment by aheckmann** [comment]
I ran it on Ubuntu I think (it's been a while).

On Thu, Jan 15, 2015 at 1:52 AM, Loreto Parisi notifications@github.com
wrote:

> How did you install GraphicsMagick binaries on Azure? There's no official
> doc about this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aheckmann/channel9/issues/1.

## 

Aaron
@aaronheckmann https://twitter.com/#!/aaronheckmann
soundcloud.com/ajhecky
github.com/aheckmann

**Comment by loretoparisi** [comment]
yes I think so! Thanks, so far I have found no solution to make it work on Azure Web Site, thanks anyway for your nice tutorial!
